version: "3.4"
services:
  axreng-backend:
    container_name: app-backend
    image: app/backend:latest
    build:
      context: ../
      dockerfile: $PWD/Dockerfile
    environment:
      - BASE_URL=http://www.google.com/
      - KEYWORD=FOUR
      - MAX_RESULTS=20
    ports:
      - "4567:4567" # StandartPort
    volumes:
      - $HOME/.m2":/root/.m2
